### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by FredslundMagnus** [Apparence-io/pal-plugin#3]
![image](https://user-images.githubusercontent.com/54928264/100086990-66165b00-2e4e-11eb-8bfc-b66703e22689.png)

I use Æ/æ, Ø/ø and Å/å, but these charecters do not seem to be supported.

**Comment by g-apparence** [comment]
Thank you reporting it. We are going to support more languages, that's a good one. 
What is the locale you used for this characters plz ?

**Comment by FredslundMagnus** [comment]
It is danish, I do not use Language codes in my app, but I would guess something like this: Locale('da', 'DK')

**Comment by g-apparence** [comment]
After some digging it's our database encoding. 
We are going to fix this on the demo database to save all texts for all languages correctly.

**Comment by g-apparence** [comment]
This has been fixed and will be available soon on the production server. 
Feel free to reopen if you still got an error. 

Thank you for reporting this, this helps us make it better 👍
