### ISSUE TITLE
Error creating helpers

### ISSUE THREAD

**Issue by Psykotik** [Apparence-io/pal-plugin#4]
Hello,

I'm getting an error while creating an helper page.
Every time I click on save after editing the page, I get this error : 

![image](https://user-images.githubusercontent.com/16321347/102810718-7b869280-43c4-11eb-8952-e98272f963c3.png)

On the logs it says 
_error occured PageCreationException: EMPTY_ROUTE_PROVIDED_

What is the route mentionned ? I can't find any information in the documentation about this one.
Any help please ? 😊

**Comment by ghost** [comment]
I will take a look, thanks for reporting it 😎

**Comment by ghost** [comment]
@Psykotik The issue appear when you use ```.push()``` method instead of ```.pushNamed()``` method.

You have to create ```RouteSettings``` like this on every push methods you have in your app (be sure to create **unique** name fo each):
```dart
Navigator.push(
  context,
  MaterialPageRoute(
    settings: RouteSettings(
      name: 'page1', // <- Type here an unique route name
    )),
    builder: (context) => YourNewPage(),
);
```

**Note:** Using ```.pushNamed()``` method, Pal know automatically the route name without specified it 👍

**Comment by Psykotik** [comment]
Thanks !

Everything is working fine now. 😀
