### ISSUE TITLE
Task 'assembleRelease' not found in root project 'application icon'.

### ISSUE THREAD

**Issue by pierre-gancel** [Apparence-io/pal-plugin#6]
all was working well while debuggin on macos,
encountered this error while trying to launch the app on android,
error disappeared when I remove pal from the .yaml

Global feedback however is great,
You are building a fantastic tools guys !

**Comment by g-apparence** [comment]
Hello, Thank you for reporting it!
It's an asset error (Pal icon) that seems not available on android. Will try to reproduce and fix this asap. 

Thank you for your feedback, that's really encouraging!
Don't hesitate to suggest any features.

**Comment by ghost** [comment]
Hi @pierre-gancel do you have an example to reproduce this error ?

**Comment by pierre-gancel** [comment]
problem indeed comes from the application_icon-1.0.0 in my .pub-cache,
It is triggered when I use PAL, but could it be due to something else ?

<img width="1110" alt="Screenshot 2021-02-01 at 20 40 09" src="https://user-images.githubusercontent.com/69810198/106509259-aee13480-64cd-11eb-9f8a-a82f9e74f824.png">


```
.pub-cache/hosted/pub.dartlang.org/application_icon-1.0.0/android/src/main/kotlin/de/ju/application_icon/AppIconLoader.kt:
(71, 16): Type mismatch: inferred type is Drawable? but Drawable was expected
```

**Comment by ghost** [comment]
Thanks for your answer, it's seem to be an issue with the [application_icon](https://github.com/ueman/application_icon) library which is used in Pal.

I can't reproduce this error on a blank new project, maybe there is a library conflict in your project ? Maybe you can try to remove some dependencies in your project until the error disappear to check if this is a conflict error.

For the moment, I suggest you to raise an issue on the [application_icon](https://github.com/ueman/application_icon) repo 👍.

**Comment by pierre-gancel** [comment]
Thanks, yes done, will see.
I will revert if no reply in a few days/weeks,
Why not consider embedding this into Pal to keep it under hand ?

**Comment by g-apparence** [comment]
You are right, as for first release we used some plugins to reduce developments. 
Now we got some majors goals for the next release. Reducing the number of external dependencies(like application_icon) is now critical. 
The next release is on a big backend migration (we migrated our data to cassandra)... and plenty of cool features for the editor mode. We will try to include this ASAP.

**Comment by ueman** [comment]
I've just fixed https://github.com/ueman/application_icon/issues/5. 
Your users have to run `pub upgrade` and it should work again.

**Comment by g-apparence** [comment]
Wow thank you, that's really kind of you!
Did you migrate to null safety? 
We also have to migrate to null safety soon.

**Comment by ueman** [comment]
Not yet, but it shouldn't be too hard as it not much code. I would gladly accept a PR if you are open to that. The native side is already null safe because auf Swift and Kotlin.
