### ISSUE TITLE
504 error on web-site

### ISSUE THREAD

**Issue by tsinis** [Apparence-io/pal-plugin#7]
Hey @g-apparence!

I was tried to register on https://en.apparence.io/pal-plugin.tech but it's only showing 504 error now. Any chance to fix it? I'm very excited to check your tool.

P.S. is the code you provide with your tool null-safety ready? Thanks

Best regards,
Roman

**Comment by g-apparence** [comment]
Hi, 
where did you see that link?
The correct link is : http://demo.pal-plugin.tech

Thank you for your encouragement! :)

**Comment by g-apparence** [comment]
(found this broken link in our website article, fixed it). 

Feel free to open an issue if you need anything.
