### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by pierre-gancel** [Apparence-io/pal-plugin#8]
I don't know if web support is planned,
got the problem below
<img width="1100" alt="Screenshot 2021-02-08 at 14 39 59" src="https://user-images.githubusercontent.com/69810198/107227320-869c8d00-6a1b-11eb-9e03-ec2e98ce39b5.png">

**Comment by g-apparence** [comment]
Hello Pierre,
for next step, we are more planning on macos / windows support as flutter web seems more unstable. 
Maybe the next announcement will change that... 
Will make a try with the web support, I'm curious. ^^

**Comment by g-apparence** [comment]
Closed because now Pal is working on every Platforms 🎉
